### ISSUE TITLE
Add gas mask

### ISSUE THREAD

**Issue by bmds** [code-computerlove/dotfiles#12]
**What is it?**
Light weight hosts manager for OSX

**Where can i find it?**
https://github.com/2ndalpha/gasmask

**Why should we include it?**
When dealing with remote machine & windows VMs a simple way to manage your host alias saves loads of time

**Cask command?**
` brew cask install gas-mask`
https://github.com/caskroom/homebrew-cask/blob/master/Casks/gas-mask.rb

**Comment by furzeface** [comment]
Yep I agree - I've found it useful before, want to add it and PR?
